esphome:
  name: radiator-fan-controller
  friendly_name: Radiator Fan Controller

esp8266:
  board: d1_mini

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Radiator Fan Controller"
    password: "ixiXvxthEx4m"

captive_portal:
web_server:

output:
  - platform: esp8266_pwm
    pin: D4
    frequency: 20000 Hz
    id: pwm_output

fan:
  - platform: speed
    output: pwm_output
    name: Fan
    id: fan_1
